from .classes import LocationData, Token, Pearl
from ..conditions import generate

locations: list[LocationData] = [
    Token("SU", "gold", "SU", 0, ""),
    Token("SU", "red", "SU", 1, ""),
    Token("PoleMimic", "blue", "SU", 2, ""),
    Token("DangleFruit", "blue", "SU", 3, ""),
    Token("CicadaA", "blue", "SU", 4, ""),
    Pearl("SU", "", "SU", 20, ""),
    Pearl("SU_filt", "", "SU^", 21, ""),

    Token("HI", "gold", "HI", 100, ""),
    Token("HI", "red", "HI", 101, ""),
    Token("FirecrackerPlant", "blue", "HI", 102, ""),
    Token("BlueLizard", "blue", "HI", 103, ""),
    Token("SmallCentipede", "blue", "HI", 104, ""),
    Token("VultureGrub", "blue", "HI", 105, ""),
    Pearl("HI", "", "HI", 120, ""),

    Token("DS", "gold", "DS", 200, "B10"),
    Token("DS", "red", "DS", 201, "A01"),
    Token("Snail", "blue", "DS", 202, "B06"),
    Token("Salamander", "blue", "DS", 203, "B04"),
    Token("Leech", "blue", "DS", 204, "A05"),
    Token("BubbleGrass", "blue", "DS", 205, "A25"),
    Token("Hazer", "blue", "DS", 206, "A21"),
    Pearl("DS", "", "DS", 220, ""),

    Token("GW", "gold", "GW", 300, "C10"),
    Token("GW", "red", "GW", 301, "A25"),
    Token("WaterNut", "blue", "GW", 302, "D02"),
    Token("RedLizard", "blue", "GW", 303, "A14"),
    Token("BrotherLongLegs", "blue", "GW", 304, "C09",
          generation_condition=generate.blacklist_scugs(["Saint"])),
    Token("ScavengerBomb", "blue", "GW", 305, "A21"),
    Token("FireSpear", "blue", "GW", 306, "A24"),
    Pearl("GW", "", "GW", 320, ""),

    Token("SL", "red", "SL", 401, "I01"),
    Token("SeaLeech", "blue", "SL", 402, "A06"),
    Token("BigEel", "blue", "SL", 403, "E01"),
    Token("JetFish", "blue", "SL", 404, "F02"),
    Token("JellyFish", "blue", "SL", 405, "C01"),
    Pearl("SL", "", "SL", 420, ""),
    Pearl("SL_chimney", "", "SL", 421, ""),
    Pearl("SL_moon", "", "SL", 422, ""),

    Token("VS", "gold", "VS", 500, "C04"),
    Token("VS", "red", "VS", 501, "E02"),
    Token("Pearl", "blue", "VS", 502, "A14"),
    Token("LillyPuck", "blue", "VS", 503, "C03"),
    Pearl("VS", "", "VS", 520, ""),

    Token("SH", "gold", "SH", 600, "B04"),
    Token("SH", "red", "SH", 601, "KELP"),
    Token("BigSpider", "blue", "SH", 602, "A13"),
    Token("Spider", "blue", "SH", 603, "C03"),
    Token("Lantern", "blue", "SH", 604, "B05"),
    Token("LanternMouse", "blue", "SH", 605, "B05"),
    Token("MirosBird", "blue", "SH", 606, "E01"),
    Token("FlareBomb", "blue", "SH", 607, "D03"),
    Pearl("SH", "", "SH", 620, "A19"),

    Token("UW", "red", "UW", 701, "D06"),
    Token("YellowLizard", "blue", "UW", 702, "C02"),
    Token("SlimeMold", "blue", "UW", 703, "J01"),
    Token("TubeWorm", "blue", "UW", 704, "B01"),
    Pearl("UW", "", "UW", 720, "H01"),

    Token("SS", "red", "SS", 801, "E06"),
    Token("Inspector", "blue", "SS", 802, "C03"),

    Token("CC", "gold", "CC", 900, "STRAINER01"),
    Token("CC", "red", "CC", 901, "OUTPUT"),
    Token("DropBug", "blue", "CC", 902, "F01"),
    Token("WhiteLizard", "blue", "CC", 903, "A10"),
    Token("CyanLizard", "blue", "CC", 904, "C13"),
    Token("Vulture", "blue", "CC", 905, "C04"),
    Pearl("CC", "", "CC", 920, ""),

    Token("SI", "gold", "SI", 1000, "C07"),
    Token("SI", "red", "SI", 1001, "B09"),
    Token("VultureMask", "blue", "SI", 1002, "B07x"),
    Token("KingVulture", "blue", "SI", 1003, "A07"),
    Token("Centiwing", "blue", "SI", 1004, "A18"),
    Token("EggBug", "blue", "SI", 1005, "D05"),
    Token("DandelionPeach", "blue", "SI", 1006, "C04"),
    Pearl("SI_top", "", "SI", 1020, "A07"),
    Pearl("SI_west", "", "SI", 1021, "B12"),
    Pearl("SI_chat3", "", "SI", 1022, "C02"),
    Pearl("SI_chat4", "", "SI", 1023, "C08"),
    Pearl("SI_chat5", "", "SI", 1024, "B10"),

    Token("LF", "gold", "LF", 1100, "B04"),
    Token("LF", "red", "LF", 1101, "D09"),
    # Token("ScavengerBomb", "blue", "LF", 1102, "A17"),  TODO verify that this exists
    Token("SpitterSpider", "blue", "LF", 1103, "B04"),
    Token("Deer", "blue", "LF", 1104, "C03"),
    Token("FlyLure", "blue", "LF", 1105, "D06"),
    Token("SporePlant", "blue", "LF", 1106, "D02"),
    Token("BigNeedleWorm", "blue", "LF", 1107, "A02"),
    Token("PuffBall", "blue", "LF", 1108, "F02"),
    Pearl("LF_west", "", "LF", 1120, "D06"),
    Pearl("LF_bottom", "", "LF", 1121, "D07"),

    Token("SB", "gold", "SB", 1200, "F01"),
    Token("SB", "red", "SB", 1201, "J01"),
    Token("Filtration", "gold", "SB", 1202, "G04"),
    Token("BigCentipede", "blue", "SB", 1203, "G02"),
    Token("TentaclePlant", "blue", "SB", 1204, "J03"),
    Token("BlackLizard", "blue", "SB", 1205, "D04"),
    Token("Mushroom", "blue", "SB", 1206, "E04"),
    Token("RedCentipede", "blue", "SB", 1207, "H02"),
    Pearl("SB_ravine", "", "SB^", 1220, "F03"),
    # Pearl("Misc2", "", "SB", 1221, "E07"),  TODO verify that this actually a unique pearl
    Pearl("SB_filtration", "", "SB", 1222, "J03"),

    Token("MS", "gold", "MS", 1300, "FARSIDE"),
    Token("MS", "red", "MS^", 1301, "bittermironest"),
    Token("BigJelly", "blue", "MS", 1302, "MEMOUTSIDE"),
    Token("GlowWeed", "blue", "MS", 1303, "VENT15"),
    Token("AquaCenti", "blue", "MS", 1304, "VENT10"),
    Token("Rivulet", "green", "MS", 1305, "VISTA", generation_condition=generate.whitelist_scugs(["Rivulet"])),

    Token("OE", "gold", "OE", 1400, "WORMPIT"),
    Token("OE", "red", "OE", 1401, "TREETOP"),
    Token("SlugNPC", "blue", "OE^", 1402, "PUMP04"),
    Token("Spit Lizard", "blue", "OE", 1403, "RUIN25"),
    Token("Yeek", "blue", "OE", 1404, "RUIN21"),
    Token("GooieDuck", "blue", "OE", 1405, "JUNGLE04"),
    Token("JungleLeech", "blue", "OE", 1406, "RUIN06"),
    Token("Gourmand", "green", "OE", 1407, "CAVE13", generation_condition=generate.whitelist_scugs(["Gourmand"])),
    Pearl("OE", "", "OE", 1420, "SPIRE"),

    Token("LM", "gold", "LF", 1500, "D04"),
    Token("LM", "red", "LF", 1501, "LEGENTRANCEARTY"),
    Token("SeaLeech", "blue", "LF", 1502, "A06"),
    Token("BigEel", "blue", "LF", 1503, "E01"),
    Token("JellyFish", "blue", "LF", 1504, "C01"),
    Pearl("SL_bridge", "", "LF", 1520, "B01"),
    Pearl("SL_shimney", "", "LF", 1521, "B04"),

    Token("LC", "gold", "LC", 1600, "streets"),
    Token("LC", "red", "LC", 1601, "02A"),
    Token("Artificer", "green", "LC", 1602, "SUBWAY04"),
    Token("ElectricSpear", "blue", "LC", 1603, "scavtreasury"),
    Token("ScavengerElite", "blue", "LC", 1604, "topdoor"),
    Token("SingularityBomb", "blue", "LC", 1605, "LAC01"),
    Pearl("LC", "", "LC", 1620, "ruin01"),
    Pearl("LC second", "", "LC", 1621, "floorpipes"),

    Token("RM", "gold", "RM", 1700, "A04"),
    Token("RM", "red", "RM", 1701, "LCUPSIDE"),
    Token("TerrorLongLegs", "blue", "RM", 1702, "DEAD01"),
    Token("DaddyLongLegs", "blue", "RM", 1703, "H01"),
    Pearl("RM", "blue", "RM", 1720, "AI"),

    Token("DM", "gold", "DM", 1800, "I08"),
    Token("DM", "red", "DM", 1801, "M02"),
    Token("Spear", "green", "DM", 1802, "VISTA"),
    Token("MotherSpider", "blue", "DM", 1803, "U09"),
    Pearl("DM", "", "DM", 1820, "LAB3"),

    Token("UG", "gold", "UG", 1900, "DARK01"),
    Token("UG", "red", "UG", 1901, "C02"),
    Token("Snail", "blue", "UG", 1902, "B06"),
    Token("JungleLeech", "blue", "UG", 1903, "A16"),
    Token("Salamander", "blue", "UG", 1904, "B05"),
    Token("Hazer", "blue", "UG", 1905, "A21"),
    Token("BubbleGrass", "blue", "UG", 1906, "A25"),
    Pearl("DS", "blue", "UG", 1920, "D01"),

    Token("CL", "gold", "CL", 2000, "B21"),
    Token("CL", "red", "CL", 2001, "A36"),
    Token("Saint", "green", "CL", 2002, "LSSECRET"),
    Token("BigSpider", "blue", "CL", 2003, "A13"),
    Token("YellowLizard", "blue", "CL", 2004, "C21"),
    Token("BrotherLongLegs", "blue", "CL", 2005, "C14"),
    Token("SlimeMold", "blue", "CL", 2006, "B03"),
    Pearl("RM", "", "CL", 2020, "AI"),
]
