from .classes import LocationData, Token, Pearl
from ..conditions import generate

locations: list[LocationData] = [
    Token("SU", "gold", "Outskirts", 0, ""),
    Token("SU", "red", "Outskirts", 1, ""),
    Token("PoleMimic", "blue", "Outskirts", 2, ""),
    Token("DangleFruit", "blue", "Outskirts", 3, ""),
    Token("CicadaA", "blue", "Outskirts", 4, ""),
    Pearl("SU", "", "Outskirts", 20, ""),
    Pearl("SU_filt", "", "Outskirts filtration", 21, ""),

    Token("HI", "gold", "Industrial Complex", 100, ""),
    Token("HI", "red", "Industrial Complex", 101, ""),
    Token("FirecrackerPlant", "blue", "Industrial Complex", 102, ""),
    Token("BlueLizard", "blue", "Industrial Complex", 103, ""),
    Token("SmallCentipede", "blue", "Industrial Complex", 104, ""),
    Token("VultureGrub", "blue", "Industrial Complex", 105, ""),
    Pearl("HI", "", "Industrial Complex", 120, ""),

    Token("DS", "gold", "Drainage System", 200, "B10"),
    Token("DS", "red", "Drainage System", 201, "A01"),
    Token("Snail", "blue", "Drainage System", 202, "B06"),
    Token("Salamander", "blue", "Drainage System", 203, "B04"),
    Token("Leech", "blue", "Drainage System", 204, "A05"),
    Token("BubbleGrass", "blue", "Drainage System", 205, "A25"),
    Token("Hazer", "blue", "Drainage System", 206, "A21"),
    Pearl("DS", "", "Drainage System", 220, ""),

    Token("GW", "gold", "Garbage Wastes", 300, "C10"),
    Token("GW", "red", "Garbage Wastes", 301, "A25"),
    Token("WaterNut", "blue", "Garbage Wastes", 302, "D02"),
    Token("RedLizard", "blue", "Garbage Wastes", 303, "A14"),
    Token("BrotherLongLegs", "blue", "Garbage Wastes", 304, "C09",
          generation_condition=generate.blacklist_scugs(["Saint"])),
    Token("ScavengerBomb", "blue", "Garbage Wastes", 305, "A21"),
    Token("FireSpear", "blue", "Garbage Wastes", 306, "A24"),
    Pearl("GW", "", "Garbage Wastes", 320, ""),

    Token("SL", "red", "Shoreline", 401, "I01"),
    Token("SeaLeech", "blue", "Shoreline", 402, "A06"),
    Token("BigEel", "blue", "Shoreline", 403, "E01"),
    Token("JetFish", "blue", "Shoreline", 404, "F02"),
    Token("JellyFish", "blue", "Shoreline", 405, "C01"),
    Pearl("SL", "", "Shoreline", 420, ""),
    Pearl("SL_chimney", "", "Shoreline", 421, ""),
    Pearl("SL_moon", "", "Shoreline", 422, ""),

    Token("VS", "gold", "Pipeyard", 500, "C04"),
    Token("VS", "red", "Pipeyard", 501, "E02"),
    Token("Pearl", "blue", "Pipeyard", 502, "A14"),
    Token("LillyPuck", "blue", "Pipeyard", 503, "C03"),
    Pearl("VS", "", "Pipeyard", 520, ""),

    Token("SH", "gold", "Shaded Citadel", 600, "B04"),
    Token("SH", "red", "Shaded Citadel", 601, "KELP"),
    Token("BigSpider", "blue", "Shaded Citadel", 602, "A13"),
    Token("Spider", "blue", "Shaded Citadel", 603, "C03"),
    Token("Lantern", "blue", "Shaded Citadel", 604, "B05"),
    Token("LanternMouse", "blue", "Shaded Citadel", 605, "B05"),
    Token("MirosBird", "blue", "Shaded Citadel", 606, "E01"),
    Token("FlareBomb", "blue", "Shaded Citadel", 607, "D03"),
    Pearl("SH", "", "Shaded Citadel", 620, "A19"),

    Token("UW", "red", "The Exterior", 701, "D06"),
    Token("YellowLizard", "blue", "The Exterior", 702, "C02"),
    Token("SlimeMold", "blue", "The Exterior", 703, "J01"),
    Token("TubeWorm", "blue", "The Exterior", 704, "B01"),
    Pearl("UW", "", "The Exterior", 720, "H01"),

    Token("SS", "red", "Five Pebbles", 801, "E06"),
    Token("Inspector", "blue", "Five Pebbles", 802, "C03"),

    Token("CC", "gold", "Chimney Canopy", 900, "STRAINER01"),
    Token("CC", "red", "Chimney Canopy", 901, "OUTPUT"),
    Token("DropBug", "blue", "Chimney Canopy", 902, "F01"),
    Token("WhiteLizard", "blue", "Chimney Canopy", 903, "A10"),
    Token("CyanLizard", "blue", "Chimney Canopy", 904, "C13"),
    Token("Vulture", "blue", "Chimney Canopy", 905, "C04"),
    Pearl("CC", "", "Chimney Canopy", 920, ""),

    Token("SI", "gold", "Sky Islands", 1000, "C07"),
    Token("SI", "red", "Sky Islands", 1001, "B09"),
    Token("VultureMask", "blue", "Sky Islands", 1002, "B07x"),
    Token("KingVulture", "blue", "Sky Islands", 1003, "A07"),
    Token("Centiwing", "blue", "Sky Islands", 1004, "A18"),
    Token("EggBug", "blue", "Sky Islands", 1005, "D05"),
    Token("DandelionPeach", "blue", "Sky Islands", 1006, "C04"),
    Pearl("SI_top", "", "Sky Islands", 1020, "A07"),
    Pearl("SI_west", "", "Sky Islands", 1021, "B12"),
    Pearl("SI_chat3", "", "Sky Islands", 1022, "C02"),
    Pearl("SI_chat4", "", "Sky Islands", 1023, "C08"),
    Pearl("SI_chat5", "", "Sky Islands", 1024, "B10"),

    Token("LF", "gold", "Farm Arrays", 1100, "B04"),
    Token("LF", "red", "Farm Arrays", 1101, "D09"),
    # Token("ScavengerBomb", "blue", "Farm Arrays", 1102, "A17"),  TODO verify that this exists
    Token("SpitterSpider", "blue", "Farm Arrays", 1103, "B04"),
    Token("Deer", "blue", "Farm Arrays", 1104, "C03"),
    Token("FlyLure", "blue", "Farm Arrays", 1105, "D06"),
    Token("SporePlant", "blue", "Farm Arrays", 1106, "D02"),
    Token("BigNeedleWorm", "blue", "Farm Arrays", 1107, "A02"),
    Token("PuffBall", "blue", "Farm Arrays", 1108, "F02"),
    Pearl("LF_west", "", "Farm Arrays", 1120, "D06"),
    Pearl("LF_bottom", "", "Farm Arrays", 1121, "D07"),

    Token("SB", "gold", "Subterranean", 1200, "F01"),
    Token("SB", "red", "Subterranean", 1201, "J01"),
    Token("Filtration", "gold", "Subterranean", 1202, "G04"),
    Token("BigCentipede", "blue", "Subterranean", 1203, "G02"),
    Token("TentaclePlant", "blue", "Subterranean", 1204, "J03"),
    Token("BlackLizard", "blue", "Subterranean", 1205, "D04"),
    Token("Mushroom", "blue", "Subterranean", 1206, "E04"),
    Token("RedCentipede", "blue", "Subterranean", 1207, "H02"),
    Pearl("SB_ravine", "", "Subterranean ravine", 1220, "F03"),
    # Pearl("Misc2", "", "Subterranean", 1221, "E07"),  TODO verify that this actually a unique pearl
    Pearl("SB_filtration", "", "Subterranean", 1222, "J03"),

    Token("MS", "gold", "Submerged Superstructure", 1300, "FARSIDE"),
    Token("MS", "red", "Bitter Aerie", 1301, "bittermironest"),
    Token("BigJelly", "blue", "Submerged Superstructure", 1302, "MEMOUTSIDE"),
    Token("GlowWeed", "blue", "Submerged Superstructure", 1303, "VENT15"),
    Token("AquaCenti", "blue", "Submerged Superstructure", 1304, "VENT10"),
    Token("Rivulet", "green", "Submerged Superstructure", 1305, "VISTA",
          generation_condition=generate.whitelist_scugs(["Rivulet"])),

    Token("OE", "gold", "Outer Expanse", 1400, "WORMPIT"),
    Token("OE", "red", "Outer Expanse", 1401, "TREETOP"),
    Token("SlugNPC", "blue", "Outer Expanse filtration", 1402, "PUMP04"),
    Token("Spit Lizard", "blue", "Outer Expanse", 1403, "RUIN25"),
    Token("Yeek", "blue", "Outer Expanse", 1404, "RUIN21"),
    Token("GooieDuck", "blue", "Outer Expanse", 1405, "JUNGLE04"),
    Token("JungleLeech", "blue", "Outer Expanse", 1406, "RUIN06"),
    Token("Gourmand", "green", "Outer Expanse", 1407, "CAVE13",
          generation_condition=generate.whitelist_scugs(["Gourmand"])),
    Pearl("OE", "", "Outer Expanse", 1420, "SPIRE"),

    Token("LM", "gold", "Waterfront Facility", 1500, "D04"),
    Token("LM", "red", "Waterfront Facility", 1501, "LEGENTRANCEARTY"),
    Token("SeaLeech", "blue", "Waterfront Facility", 1502, "A06"),
    Token("BigEel", "blue", "Waterfront Facility", 1503, "E01"),
    Token("JellyFish", "blue", "Waterfront Facility", 1504, "C01"),
    Pearl("SL_bridge", "", "Waterfront Facility", 1520, "B01"),
    Pearl("SL_shimney", "", "Waterfront Facility", 1521, "B04"),

    Token("LC", "gold", "Metropolis", 1600, "streets"),
    Token("LC", "red", "Metropolis", 1601, "02A"),
    Token("Artificer", "green", "Metropolis", 1602, "SUBWAY04"),
    Token("ElectricSpear", "blue", "Metropolis", 1603, "scavtreasury"),
    Token("ScavengerElite", "blue", "Metropolis", 1604, "topdoor"),
    Token("SingularityBomb", "blue", "Metropolis", 1605, "LAC01"),
    Pearl("LC", "", "Metropolis", 1620, "ruin01"),
    Pearl("LC second", "", "Metropolis", 1621, "floorpipes"),

    Token("RM", "gold", "The Rot", 1700, "A04"),
    Token("RM", "red", "The Rot", 1701, "LCUPSIDE"),
    Token("TerrorLongLegs", "blue", "The Rot", 1702, "DEAD01"),
    Token("DaddyLongLegs", "blue", "The Rot", 1703, "H01"),
    Pearl("RM", "blue", "The Rot", 1720, "AI"),

    Token("DM", "gold", "Looks to the Moon", 1800, "I08"),
    Token("DM", "red", "Looks to the Moon", 1801, "M02"),
    Token("Spear", "green", "Looks to the Moon", 1802, "VISTA"),
    Token("MotherSpider", "blue", "Looks to the Moon", 1803, "U09"),
    Pearl("DM", "", "Looks to the Moon", 1820, "LAB3"),

    Token("UG", "gold", "Undergrowth", 1900, "DARK01"),
    Token("UG", "red", "Undergrowth", 1901, "C02"),
    Token("Snail", "blue", "Undergrowth", 1902, "B06"),
    Token("JungleLeech", "blue", "Undergrowth", 1903, "A16"),
    Token("Salamander", "blue", "Undergrowth", 1904, "B05"),
    Token("Hazer", "blue", "Undergrowth", 1905, "A21"),
    Token("BubbleGrass", "blue", "Undergrowth", 1905, "A25"),
    Pearl("DS", "blue", "Undergrowth", 1920, "D01"),

    Token("CL", "gold", "Silent Construct", 2000, "B21"),
    Token("CL", "red", "Silent Construct", 2001, "A36"),
    Token("Saint", "green", "Silent Construct", 2002, "LSSECRET"),
    Token("BigSpider", "blue", "Silent Construct", 2003, "A13"),
    Token("YellowLizard", "blue", "Silent Construct", 2004, "C21"),
    Token("BrotherLongLegs", "blue", "Silent Construct", 2005, "C14"),
    Token("SlimeMold", "blue", "Silent Construct", 2006, "B03"),
    Pearl("RM", "", "Silent Construct", 2020, "AI"),
]
